-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 29-10-2024 a las 17:25:09
-- Versión del servidor: 10.4.27-MariaDB
-- Versión de PHP: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `sigob`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `descripcion_programas`
--

CREATE TABLE `descripcion_programas` (
  `id` int(255) NOT NULL,
  `id_sector` int(255) NOT NULL,
  `id_programa` int(255) NOT NULL,
  `descripcion` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `descripcion_programas`
--

INSERT INTO `descripcion_programas` (`id`, `id_sector`, `id_programa`, `descripcion`) VALUES
(1, 1, 1, 'Con este programa se satisfacen las necesidades legislativas  del Estado, se elaboran nuevas leyes y se reforman las que  lo ameritan, así como resoluciones para obtención de medidas seguras para el buen ejercicio de la Entidad, en beneficio de la comunidad Amazonense; atendiendo necesidades tanto del sector público, como del sector privado por tratarse de leyes que afectan a toda la población.\r\n\r\n \r\nEntre otras actividades estarán la de legislar en materias de su competencia de acuerdo a la Constitución,  Leyes del Estado y la Nación, para dotarlo de instrumentos normativos legales que permitan la promoción del desarrollo integral y sustentable del Estado.\r\n'),
(2, 1, 2, 'La Contraloría del Estado Amazonas,  es el órgano de control, vigilancia y fiscalización de los ingresos, gastos y bienes públicos del Estado y a tal efecto goza de autonomía orgánica y funcional,  de conformidad con lo establecido en el articulo 163 de la Constitución de la República Bolivariana de Venezuela, sin menoscabo de la función de control, seguimiento y evaluación de la Contraloría General de la República. \r\n \r\nLa Contraloría del Estado Amazonas, ahora como órgano integrante del Sistema Nacional de Control Fiscal, el cual es un conjunto de órganos, estructuras, recursos y procesos que integrados bajo la rectoría de la Contraloría General de la República, interactúan coordinadamente a fin de lograr la unidad de dirección de los sistemas y procedimientos de control  que coadyuven al logro de los objetivos generales de los distintos entes y organismos sujetos a control fiscal, así como también al buen funcionamiento de la administración pública; cuyos objetivos son:\r\n \r\n* Fortalecer la capacidad del Estado para ejecutar eficazmente su función de gobierno.\r\n\r\n* Lograr la transparencia y la eficiencia en el manejo de los recursos del sector público   y así contribuir a optimizar la calidad de vida de la ciudadanía.\r\n\r\n* Establecer las responsabilidades por la comisión de irregularidades relacionadas con la gestión  de las entidades públicas.\r\n'),
(3, 1, 3, 'Le corresponde representar y amparar judicial y extrajudicialmente, conforme a las instrucciones emanadas del Ejecutivo Regional o del Consejo Legislativo los intereses del Estado, sus bienes, su patrimonio, rentas y derechos, redactar y suscribir conforme a las instrucciones que le fueren comunicadas por el Ejecutivo Regional, por el Consejo Legislativo, los documentos contentivos de actos, negocio o contratos que conciernan al Estado; además prestar asesoría jurídica a los órganos y dependencia del Estado.\r\n	\r\nAsistir en representación del Estado a las discusiones de los Contratos Colectivos que el Ejecutivo regional, Consejo Legislativo y sus dependencias, órganos auxiliares y conexos tengan a bien suscribir con sus trabajadores.\r\n\r\nLlevar un inventario permanente de los bienes inmuebles del Estado,  velar por el estricto  cumplimiento de las leyes, en el ámbito del estado y pedir por ante los organismos jurisdiccionales competentes la nulidad de leyes, decretos, ordenanzas, acuerdos y resoluciones dictadas en el Estado.\r\n \r\nPresentar proyectos de leyes ante el Consejo Legislativo Regional y solicitar la reforma parcial de las ya existentes, cuando ella sea pertinente a los intereses del Estado y la Nación.\r\n \r\nElaborar su propio Presupuesto de Gastos a fin de ser incluidos en el Presupuesto General de Ingresos y Gastos del Estado, y ordenar traslados de partidas y otros movimientos contables dentro de su propio presupuesto anual de gasto, conforme a lo establecido en la Ley orgánica de Administración del Estado, Ley Orgánica de Presupuesto y la Ley Orgánica de Régimen presupuestario del Estado y demás normativa vigente.\r\n'),
(4, 1, 4, 'El Gobernador del estado como Jefe del Ejecutivo Regional y Agente del Ejecutivo Nacional, tendrá las facultades previstas en la Constitución de la República, la Ley sobre Elección y Remoción de Gobernadores, Ley Orgánica de Descentralización, Delimitación y Transferencia de competencia del poder público, la Constitución del Estado Amazonas y las otras normativas legales vigentes.\r\n \r\n \r\nEl propósito de este programa, es responder en el más alto nivel, el estricto cumplimiento de todas las actividades que sean necesarias para Gobernar el Estado Amazonas y para coordinar acciones administrativas y sociales, en función del desarrollo económico y social sustentable del Estado.\r\n'),
(5, 1, 6, 'Es el órgano directo e inmediato del Gobernador a cuyo cargo esta la supervisión de las actividades administrativas del Ejecutivo del Estado Amazonas, conforme a las directrices que le imparta el Gobernador. El Secretario Ejecutivo Regional, en lo político y administrativo, tanto en el ámbito interno como municipal.\r\n \r\nDentro de las funciones del Secretario Ejecutivo de Coordinación, esta en velar por el estricto cumplimiento de todas las normas que rige la administración y vigilancia del patrimonio del Estado.\r\n \r\nSon atribuciones además, del Secretario Ejecutivo de Coordinación, mantener relaciones institucionales con el Consejo legislativo, las autoridades Municipales, los órganos de la Administración Nacional, el Clero, las Organizaciones Políticas, Sindicales, Gerencia e Empresariales y en General con todo los Sectores representativos de las comunidades que conforman el Estado en representación del Gobierno.\r\n \r\nEs de su competencia, coordinar el trabajo de las secretarías del Ejecutivo, oficinas auxiliares del Despacho de la Gobernación y las actividades de los Comisionados y las Comisiones que el Gobernador designe conforme a la Ley.\r\n \r\nConducir los procesos de ajuste de la estructura organizativa de la Gobernación, en procura de elevar la eficiencia de su gestión.\r\n'),
(6, 1, 6, 'Este programa tiene como atribuciones, la aplicación de las normas y principios que rigen la administración del personal, como elemento fundamental de funcionamiento del Gobierno Estadal.\r\n \r\n \r\nAdministra la Ejecución de los Contratos Colectivos, coordinando las relaciones obreros patronales, en el cumplimiento de las cláusulas y convenios, así como la aplicación de las Leyes y Reglamentos que rigen las normas y procedimientos administrativos en lo concerniente a la materia de recursos humanos.\r\n'),
(7, 1, 7, 'Asistir y asesorar al Gobernador del Estado, en todo lo concerniente a la Planificación y Administración Presupuestaria de la Gestión, e igualmente a las diferentes secretarías y oficinas dependientes del Ejecutivo Regional y demás poderes públicos, cuando estos lo soliciten. \r\n \r\nFormular en coordinación con la estructura del Ejecutivo Regional el proyecto de Ley de Presupuesto. \r\n \r\nEjercer la Secretaría Técnica del Comité de Planificación y Coordinación de Políticas Públicas e integrar las comisiones de trabajo a las cuales sea designado por el Gobernador para la elaboración del Plan Operativo Anual y Plan Estadal de Desarrollo Estadal.  \r\n'),
(8, 1, 8, 'El programa Servicios de Administración, se encarga de ejecutar en el marco de la norma financiera el presupuesto del Estado.\r\n \r\n \r\nCoordinar los servicios de compras de bienes y servicios; el registro del patrimonio de la Gobernación y de reproducción e imprenta.\r\n \r\n \r\nAdelantar la contabilidad fiscal del Ejecutivo Regional, de acuerdo a las pautas establecidas en la Ley.\r\n'),
(9, 1, 9, 'El objeto de este programa, es el registro, control y cancelación de los  compromisos adquiridos por la Gobernación del Estado, a través de sistemas que aseguren el adecuado manejo del Tesoro Público; así como también, el control de valores en custodia, la existencia del Tesoro y la recaudación de los fondos provenientes de la renta de diversas índoles, cumpliendo con lo dispuesto en la ley Orgánica de régimen Presupuestario, Ley General de Venta y  Gastos públicos del Estado, Ley Orgánica de Contraloría General del Estado y demás normativas vigentes de este Estado.\r\n \r\n \r\nRealiza además, todo los pagos ejecutado por Gobernación, a través de las diferentes cuentas habilitadas, Promueve actividades laborales para organizar todas las operaciones de recaudación,  custodia de valores y velar por el fiel cumplimiento de acuerdo a las disposiciones legales vigentes.\r\n'),
(10, 1, 12, 'La Secretaría De Control y Seguimiento de Gestión Pública que Ejercerá el Control y La Fiscalización de La Gestión Pública Desarrollada por la Gobernación del Estado Amazonas con el fin de dar cumplimiento Efectivo y Eficiente de los objetivos y Metas de este Ente Gubernamental\r\nFUNCIONES DE LA SECRETARÍA DE CONTROL Y SEGUMIENTO DE GESTION PÚBLICA:\r\n\r\n\r\nVelar por el cumplimiento de las políticas y directrices dictadas por el ejecutivo regional.\r\n\r\nSupervisar las actividades de las Secretarías Ejecutivas y las distintas dependencias de la Gobernación del Estado Amazonas de acuerdo a las directrices impartidas por el ciudadano Gobernador del Estado.\r\n\r\n Dar seguimiento a los proyectos o programas a ejecutar por parte del ejecutivo regional.\r\n'),
(11, 1, 10, 'Elaborar el programa anual de política indigenista, previa consulta con las comunidades, pueblos y grupos étnicos indígenas orientados al mejoramiento de las condiciones de vidas, trabajo y salud, así como su nivel educativo.\r\n \r\nSupervisar  y hacer cumplir las directrices de las políticas indigenistas.\r\n \r\nOrientar a la población indígena, sobre su organización y el establecimiento de cooperativa de producción y consumo.\r\n \r\nDefender y hacer respetar los derechos de los indígenas consagrados en la Constitución Nacional, Constitución Estadal, Leyes Nacionales y en tratados Internacionales ratificados por Venezuela.\r\n \r\nCoordinar los recursos y las acciones dirigidas a promover en las poblaciones indígenas del Estado Amazonas\r\n \r\nEstablecer nexos con los entes públicos, Nacionales  y Regionales, que hacen vida activa en el Estado Amazonas, a fin  de coordinar acciones a favor de las comunidades indígenas, a través de los diferentes Institutos Crediticios Nacionales y Estadales. \r\n\r\nDesarrollar acciones en las comunidades indígenas que contribuyan al desarrollo socio-económico y la autogestión\r\n'),
(12, 1, 13, 'Funciones de la Secretaria Ejecutiva de bienes y servicios:\r\n Dirigir, coordinar y establecer estrategia de recepción, entrega y movilización de bienes muebles adquiridos por la Gobernación para el equipamiento de las unidades administrativas.\r\nRealizar y Ejecutar periódicamente programa de actualización de inventarios de bienes asignados a distintas oficinas, tanto en las unidades administrativas dependientes como en los entes coordinados.\r\nDiseñar, controlar y supervisar, la vigilancia y resguardo de los bienes e instalaciones que son propiedades patrimoniales de la Gobernación.\r\nLlevar registro y control de bienes muebles e inmuebles, así como rendir informe a la administración y tesorería sobre el registro contable para el ajuste periódico a la hacienda pública del estado.\r\nRealizar el control perceptivo, que permita captar la veracidad, exactitud y calidad de obras, bienes y servicios. Para así verificar la sinceridad y correcta realización de las operaciones administrativas, a través de comprobación in situ.\r\n'),
(13, 1, 11, 'Los servicios de Control y Gestión comprenden el plan de organización, las políticas, normas, métodos y procedimientos adaptados dentro de un ente u organismo, sujeto a la Ley del Estatuto de la función pública, para  salvaguardar sus recursos, verificar su exactitud y veracidad de la información financiera y administrativa y promover la eficiencia económica y la calidad en sus operaciones. Estimular la observancia de las políticas, presentar y lograr el cumplimiento de misión, objetivos y metas.\r\n \r\nRealizar actividades de coordinar y dirigir los programas de auditoria a efectuarse en los organismos públicos, centralizados, dependientes financiera y presupuestariamente de la Gobernación del Estado Amazonas.\r\n \r\nEn materia de asuntos legales, el Auditor Interno de acuerdo a los casos presentados y a las situaciones que se origen en el ámbito administrativo y financiero, ordenará las aperturas, investigaciones y averiguaciones administrativas que amerite el caso.\r\n'),
(14, 2, 14, 'En este programa se desarrollan acciones tendentes para el rescate y mejora de la imagen institucional, mediante la ejecución de todas las actividades en lo referente a seguridad, defensa y orden público en primer orden y en otro sentido, en lo que al aspecto administrativo se refiere; cumpliendo eficientemente con la misión encomendada por el Despacho Superior durante todo el año, apoyando el plan de equipamiento general, con el adiestramiento y capacitación de todo el personal policial, técnicos,  administrativos y obreros e igualmente con los recursos logísticos y financieros necesarios para su completa confiabilidad.\r\n'),
(15, 2, 15, 'Esta unidad ejecutora tiene como finalidad la coordinación de programas dirigidos a resguardar la seguridad y orden público, cumplir y hacer cumplir los decretos, ordenanzas, resoluciones y demás disposiciones que la Gobernación imparta de acuerdo a la ley.\r\n \r\nCoordinar con los organismos competentes la implantación de medidas de resguardo de la colectividad afectada por calamidades públicas, el servir de enlace entre el Ejecutivo y las Fuerzas Armadas Policiales y demás organismos de Seguridad del Estado.\r\n \r\nEn otro orden de acción también se dedica  a la administración de asuntos civiles y preparar el personal policial, profesional técnico y obreros para coadyuvar al cumplimiento del orden público.  \r\n'),
(16, 2, 16, 'El objetivo primordial de este programa se puede resumir en tres funciones principales:\r\n \r\n- Actuar cordialmente para reducir al mínimo las  calamidades públicas por causas naturales.\r\n \r\n- Coordinar acciones preventivas y asistenciales.\r\n \r\n- Coordinar operativos en épocas festivas y de asueto para evitar perdida de vida.\r\n'),
(17, 2, 17, 'El Cuerpo de Bomberos del Estado Amazonas, tiene como finalidad prestar sus servicios encaminados a la seguridad en lo referente a la prevención, protección, combate, extinción de incendios y otros siniestros, así como también, la investigación de las causas y su origen, la atención de emergencias pre-hospitalaria, los servicios de rescate y salvamento y la participación en los programas para la atención de emergencias o desastre dirigida a la formación de la comunidad.\r\n \r\nLos Bomberos utilizan métodos para proteger mercancías, objetos y el interior de edificios de los daños que puedan sufrir por fuego y el agua, los objetos se cubren con material impermeable y el agua se evacua con aspiradores de agua, sumideros y bombas portátiles. La mayoría de las unidades de bomberos disponen de equipos de salvaguardia.\r\n'),
(18, 3, 18, 'La Secretaría de turismo, es el órgano ejecutor de la política turística y recreativa del Estado, a través de la cual contribuirá al desarrollo económico y social de la región, proponiendo el uso racional de los atractivos turísticos que existen en el Estado.\r\n \r\nLa riqueza y abundancia de paisajes naturales presentes en el Estado, define una amplia potencialidad turística, recreacional y contemplativa.\r\n \r\nPor lo que corresponden a este sector  la planificación y realización de programas y acciones para  que la actividad turística se convierta en una de las fuentes fundamentales para propiciar  el desarrollo económico, social y cultural del  Estado Amazonas.\r\n \r\nEn tal sentido las acciones concretas a desarrollar serán destinadas a delimitar y promover las áreas de  mayor porvenir turismo, así como la creación y mantenimiento de la infraestructura necesaria para su desarrollo. Además, dentro de estas acciones están comprendidas, velar por el mantenimiento y conservación de las instalaciones ya existentes y coordinar acciones con los organismos responsables de administrar las zonas  ABRAE del Estado con el objetivo de incorporarlas al patrimonio de uso  turístico.\r\n'),
(19, 4, 19, 'Esta Unidad programática tiene como función garantizar el cumplimiento  del proceso educativo, para el logro de la educación Integral de los ciudadanos  del procedo educativo, para el logro de  la Educación Integral de los ciudadanos del Estado.\r\n \r\nPropicia y estimula la modernización de los sistemas administrativos, con el  fin de lograr los objetivos deseados en el sector educativo.\r\n \r\nEstablece convenios con los institutos que hacen vida activa en la región, a fin de implementar procedimientos que permitan capacitar y orientar al docente.\r\n'),
(20, 4, 20, 'Este programa comprende el área de la docencia y el apoyo técnico que imparte  en los centros educacionales urbanos y rurales del Estado. A través del mismo, se mantiene el servicio de educación pre-escolar y básica, además de la coordinación de comedores escolares.\r\n \r\nEn esta unidad programática, se reflejan los beneficios que por Contratación Colectiva reciben los trabajadores de la enseñanza dependiente del Ejecutivo Regional, con la intención de mejorar la calidad de la educación en el Estado Amazonas. También se llevan a cabo programas de asistencia al indígena de alfabetización. También se lleva a cabo programas de asistencia al indígena de alfabetización, asistencia integral a los centros educacionales y de supervisión, igualmente se le brinda apoyo a la Zona Educativa.\r\n'),
(21, 5, 22, 'La Secretaria de Información y Comunicación SICOAMA tiene como objetivo principal lograr que  el pueblo sea el  vocero principal de la gestión de gobierno Pueblo-Gobierno a través de la creación innovadora y permanente de canales de comunicación con énfasis en la retroalimentación que sirvan para la consolidación de una nueva forma de gobierno que rompa los paradigmas de la democracia representativa resolviendo los problemas que le impiden a Amazonas lograr su desarrollo político, económico y social. Entre sus funciones:\r\n \r\nDiseñar la política comunicacional del Gobierno de Amazonas, de acuerdo a los lineamientos establecidos por el Gobernador.\r\nPlanificar y ejecutar las acciones destinadas a consolidar la política comunicacional del Gobierno de Amazonas.\r\nCoordinar la acción conjunta de los medios oficiales para el cumplimiento de los lineamientos comunicacionales previstos por los niveles de gobierno nacional y regional.\r\nDiseñar, ejecutar y hacer seguimiento del Plan Operativo Anual de la Secretaría de Información y Comunicación del estado Amazonas.\r\n'),
(22, 5, 23, 'La  Biblioteca Nacional de Venezuela, ha desarrollado el sistema de Biblioteca pública como parte de una estrategia orientada a brindar a la población, el más amplio acceso a la  información que requiere.\r\n\r\nPartiendo de esta concepción y para optimizar el uso de los recursos disponibles se  ha desarrollo un modelo de redes Estadales cuya estructura medular la constituye la Biblioteca Pública Central.\r\n \r\nLos servicios Bibliotecarios públicos representan los medios eficaces para lograr la atención y satisfacción de las necesidades de información, aprendizaje y recreación de la población. La cobertura de la red en el Estado amazonas cubre todos los municipios, teniendo como objetivo principal:\r\n\r\n- Dotar a la entidad de una infraestructura de servicios bibliotecarios, dirigida a tender necesidades básicas de información, conocimiento y recreación de la comunidad.\r\n\r\n- Formar adecuadamente a los usuarios para que obtengan mejores beneficios de la información.\r\n\r\n- Promover el uso de la lectura y de la información como instrumento para el desarrollo individual y colectivo.\r\n\r\n- Apoyar a la educación en todos sus niveles y en especial, la educación y la investigación. \r\n'),
(23, 5, 24, 'La Secretaría de Cultura y Comunicación, es la encargada de promover, fomentar y conservar los valores culturales de la región. A través de la Dirección y Coordinación de la Cultura de la Gobernación del Estado Amazonas, se formulan y ejecutan acciones de desarrollo cultural orientadas principalmente a la investigación, difusión de actividades autóctonas y rescate  de los valores culturales propios de nuestro Estado.\r\n'),
(24, 5, 25, 'Tiene como objetivo la coordinación de los mecanismos tecnológicos que desarrolle la ciencia a través del uso y aplicación de los medios electrónicos , informáticos y telemáticos para la organización y funcionamiento institucional.\r\n \r\nTambién tiene como fin planificar, promover y aplicar las políticas públicas en materia de las tecnologías de información y comunicación de la Gobernación del Estado Amazonas y organismos adscritos.\r\n'),
(25, 6, 27, 'Coordinar la ejecucion de obras del Fondo de Compensacion Interterritorial, asi como tambien la formulacion y evaluacion de proyectos relacionados con obras dirigidas al bienestar de  la colectividad Amazonense.\r\n'),
(26, 6, 26, 'Tiene como objetivo la coordinacion, mejoramiento fomento, direccion y control de actividades relacionadas con la vivienda, desarrollo urbano y los servicios conexos. de la misma manera, formular proyectos de acondicionamiento de servicios basicos, de mantenimiento de obras y del transporte.\r\n\r\n     Coordinar la ejecucion de obras del Fondo de Compensaci{on Interterritorial, asi como tambien la formulacion y evaluacion de proyectos relacionados con obras dirigidas al bienestar de  la colectividad Amazonense.\r\n'),
(27, 7, 28, 'La implementación de este programa persigue de manera esencial lograr los objetivos de la política sanitaria y asistencial del Estado. En este sentido se lleva a cabo la ejecución de actividades tendentes a mejorar la atención médica, programa de información y orientación ciudadana e igualmente fortalecer las acciones destinadas al funcionamiento y operación de las instalaciones de los servicios de salud.\r\n'),
(28, 8, 29, 'A través de la Secretaría de Desarrollo Social, se velará por la seguridad social en el Estado Amazonas; por ende este programa tiene como objetivo general, promover el desarrollo social en la región, en coordinación con los organismos nacionales estadales públicos y privados, mediante la ejecución de actividad y programas dirigidos al mejoramiento del nivel económico, social y cultura de la comunidades indígenas, rurales y urbanas. Corresponde a la Secretaría, las siguientes funciones:\r\n \r\n- Ejecutar la política social del Gobierno Estadal.\r\n\r\n- Asistencia de las comunidades en situación de emergencia.\r\n\r\n- Apoyar la Creación y organización de cooperativas y demás instituciones destinadas a mejorar la economía popular, así como la protección de las asociaciones, sociedades y comunidades que tenga como objetivo el mejor desarrollo socio económico del Estado.\r\n\r\n- Lo relativo a la asistencia y bienestar social a cargo de la Gobernación.\r\n\r\n- Realizar actividades de promoción, coordinación y supervisión de proyectos y mantenimiento de obras comunales.\r\n'),
(29, 8, 30, 'la Secretaria Ejecutiva de Participaciòn popular, cuyo objetivo es liderar el proceso de fortalecimiento de las organizaciones comunales y sociales y la implementacion de un Sistema de Participaciòn Popular, a los fines del ejercicio del control social y la intervencion de las politicas publicas que permitan la incidencia efectiva de las comunidades en las decisiones, la transformacion de las conciencias en el interior de las masas oprimidas que conlleven a que nuestro pueblo sea constructor de su propio destino, por cuanto desde esta perspectiva, se concibe a la persona como ser social producto de las realaciones sociales, que permite que la actividad social sea un proceso como reflejo de la realidad y resultado de la reflexion consciente de esa realidad\r\n'),
(30, 8, 31, 'Este programa tiene como objetivo incluir a las personas con discapacidad para brindar atención integral a la población con vulnerabilidad para introducirlo en el ámbito laboral, en el cumplimiento de las políticas relacionadas con la discapacidad.                                              \r\n   Esta unidad programática tiene como función:\r\n- Participar en la formulación de lineamientos, políticas, planes, proyectos y estrategias en materia de atención a personas con limitaciones físicas.\r\n- Promover la participación ciudadana en lo social y en lo económico a través de los comités comunitarios, asociaciones, cooperativas, empresas comunitarias y de cogestión y autogestión,en función de la organización de las personas con discapacidad, que conlleve a una mejor articulación e identificación con los organos y entes de la administración pública nacional, estadal y municipal, así como también a las personas naturales y jurídicas    de derecho privado.\r\n- La prestación de servicios asistenciales en materia jurídica, social y cultural a las personas con discapacidad. \r\n- Conocer sobre situaciones de discriminación a las personas con discapacidad y tramitarlas ante las autoridades competentes.\r\n'),
(31, 8, 32, 'A través de atención integral a la mujer, familia e igualdad de genero , se garantizará la igualdad de oportunidades de la mujer, para promover la participación protagónica de la mujer en los ámbitos políticos, económicos y sociales tanto a nivel regional como nacional. Entre sus funciones principales se encuentran:\r\n- Participar, planificar e instrumentar lineamientos, políticas, planes, proyectos y estrategias en materia de atención integral a la mujer, familia e igualdad de genero, dirigido al empoderamiento de las mujeres en materia jurídica, social, cultural, política, económica y recreativa, especialmente de las mujeres indígenas, campesinas, afrodescientes, pescadoras, obreras, con discapacidad, en situaciones de indigencia, desplazadas, las privadas de libertad, las amas de casa, la tercera edad, las niñas y adolescentes para garantizarles el pleno ejercicio de su libertad y el desarrolllo de sus capacidades y destrezas en una sociedad democrática, participativa, protagónica, igualitaria y socialista.\r\n- Atender y orientar a través de programas de rehabilitación a los hombres procesados en materia de violencia de genero, coordinadamente con la fiscalía del Ministerio Público, la unidad de atención a la victima y los tribunales penales en materia de violencia de genero.\r\n- Conocer sobre situaciones de discriminación contra las mujeres y tramitarlas a las autoridades competentes.\r\n'),
(32, 9, 33, 'Este programa tiene entre sus funciones: planificar, coordinar y administrar con objetividad las políticas destinadas a la seguridad social del personal activo de la Gobernación del Estado. De acuerdo a las normativas laborales y otras leyes vigente para tal fin.\r\n'),
(33, 10, 34, 'Controla de manera idónea los créditos presupuestarios asignados a las partidas de Compromisos Pendientes de Ejercicios anteriores, rectificaciones al presupuesto y otras transferencias a entes descentralizados necesarias para el mejor desenvolvimiento de la gestión pública.\r\n');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `descripcion_programas`
--
ALTER TABLE `descripcion_programas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `descripcion_programas`
--
ALTER TABLE `descripcion_programas`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
